# -*- coding: utf-8 -*-
"""CypherHack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkIKrkcYZQVY0E_zqql_8i-mbXv6lLmo
"""

import urllib3
import urllib

# urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
http = urllib3.PoolManager()
r = http.request('https://www.google.com/')

user_agent = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'

url = "https://stackoverflow.com/questions/13303449/urllib2-httperror-http-error-403-forbidden"
headers={'User-Agent':user_agent,} 

request=urllib.request.Request(url,None,headers) #The assembled request
response = urllib.request.urlopen(request)
data = response.read() # The data u need
print(data)





import requests 
URL = "https://spankbang.com/"
r = requests.get(URL) 
print(r.content)

import requests 
from bs4 import BeautifulSoup 
  
URL = "https://spankbang.com/"
r = requests.get(URL) 
  
soup = BeautifulSoup(r.content, 'html5lib') 
print(soup.prettify())

import requests 
from bs4 import BeautifulSoup 
import csv 
  
URL = "https://spankbang.com/users/auth?ajax=1&register=1"
client = requests.session()
r = client.get(URL)
form = soup.find(id="auth_register_form")

    
params={
    'r_username' : 'tsm110',
    'r_email' : 'abc@gmail.com',
    'r_password' : 'xdcfvgbhjnmk,l.',
    'r_source': 'header',
    'csrf_token': '',
# ImNjZDBmZGY3NzA5ZTA3MjdkNzQ0NGUyZjVkM2ExZjNiOTMyZWJkNTEi.XlnwQw.F6Ox8lmkD1Do-4ulT3ISaW3yiRM
}

# cookie = {
#     '__cfduid':'d95b84e200d748852789f84a80561b2fc1582946381	', 
#     'backend_version':'master', 
#     '_ga':'GA1.2.766221674.1582946383	',
#      '_gid':'GA1.2.1539252219.1582946383',
#      'ana_sid':'8b1a5ebf951d35e8453497fb210e27938fe57b355499e1f21b7a6cd4fb6c718e', 
#      'ana_vid':'8b1a5ebf951d35e8453497fb210e27938fe57b355499e1f21b7a6cd4fb6c718e',
#      'sb_session':'.eJwljEEKhDAMAP-S8x5qWwn6g734BbFNAiKmUuNBxL9vYY8zMPPAfHDdF2U1GK1e_IFcLrV6wwjfCRqeVWYrG2szOZMTEkQ3sEOPhDFG9tJTWDoJaQieE_Vd65hWW4v-N-8PKRAg2A.XlnwQw.cL_srVLI8lqXmOVBFgBE5VSIaS4	',
# }

response = requests.post(URL, data=params, cookies=client.cookie)
print(response.text)

# # soup = BeautifulSoup(r.content, 'html5lib') 
  
# # fetish=[]  # a list to store quotes 
  
# # table = soup.find('input', attrs = {'id':'reg_email'}) 
# # print (table)

# # a = requests.post()

import requests
LOGIN_URL = 'https://spankbang.com/users/auth?ajax=1&register=1'
headers = {
    'accept': 'text/html,application/xhtml+xml,application/xml',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36'
}

response = requests.get(LOGIN_URL, headers=headers, verify=False)

headers['cookie'] = '; '.join([x.name + '=' + x.value for x in response.cookies])
headers['content-type'] = 'application/x-www-form-urlencoded'
payload = {
    'username': 'user_name',
    'password': 'randompass123'
}

response = requests.post(LOGIN_URL, data=payload, headers=headers, verify=False)
headers['cookie'] = '; '.join([x.name + '=' + x.value for x in response.cookies])



#Final Spankbang

import requests 
from bs4 import BeautifulSoup 
import csv 
  
URL = "https://spankbang.com/users/auth?ajax=1&register=1"
client = requests.session()
r = client.get(URL)
soup = BeautifulSoup(r.content, 'html5lib') 
table = soup.find('input', attrs = {'id':'csrf_token'})

myobj = {"r_username":"abcd",
         "r_password":"123456",
         "r_email":"abc@gmail.com",
         "r_source":"header",
         "csrf_token":table['value']
        }

x = requests.post(URL, data = myobj,cookies = client.cookies)
#print(x.text)

soup2 = BeautifulSoup(x.content, 'html5lib')
#print(soup2)
table_temp = soup2.findAll("p")
print(table_temp)
for i in table_temp:
    if "email" in i.text:
      print(True)





import requests
from bs4 import BeautifulSoup 
import csv

URL = "https://www.playrummy.com/mobileLogin.php"

client = requests.session()
r = client.get(URL)

soup = BeautifulSoup(r.content, 'html5lib')
table = soup.find(text="Error: Password Doesn't Match Against the Email ID.")
print(table)